name: CI/CD Pipeline

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときにトリガーされる
  pull_request:
    branches:
      - main # mainブランチへのPRでトリガーされる

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage # テストを実行

      - name: Build project
        run: npm run build # ビルドを実行

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # mainブランチへのプッシュ時に実行
        run: npm run deploy # デプロイを実行
